export const mockTreeData = [
  {
    // children: [
    //   {
    //     name: 'matter_group',
    //     ifExists: 1,
    //     pid: 65,
    //     id: 2930,
    //     status: 1,
    //   },
    // ],
    name: 'robot_hive_db',
    dbType: 'Hive',
    pid: 0,
    id: 65,
  },
  {
    // children: [
    //   {
    //     name: 'hive_matter_info',
    //     ifExists: 1,
    //     pid: 56,
    //     id: 2796,
    //     status: 1,
    //   },
    //   {
    //     name: 'web_hive_test',
    //     ifExists: 1,
    //     pid: 56,
    //     id: 2792,
    //     status: 1,
    //   },
    // ],
    name: 'default',
    dbType: 'Hive',
    pid: 0,
    id: 56,
  },
  {
    // children: [
    //   {
    //     name: 'cmb_api_app_key',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1825,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_apply_api_permission_apis',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1826,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_apply_api_permission_check_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1827,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_apply_api_permission_flow',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1828,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_apply_api_permission_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1829,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_apply_kafka_cluster_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1830,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_apply_kafka_topic_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1831,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_apply_kafka_topic_order_topic',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1832,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_category_to_api',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1833,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_category_to_kafka',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1834,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_category_to_topic',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1835,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_category',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1836,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_category_link',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1837,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_rule',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1838,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_rule_detail',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1839,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_rule_job',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1840,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_rule_job_detail',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1841,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_rule_link_job',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1842,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_data_quality_subscribe',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1843,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_database',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1844,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_datasource_filed_description',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1845,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_datasource_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1846,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_datasource_kafka',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1847,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_datasource_table',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1848,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_dataview_cabinet',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1849,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_dataview_machine_room',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1850,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_db_conf',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1851,
    //     status: 0,
    //   },
    //   {
    //     name: 'cmb_api_db_table_change_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2405,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_demand',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1852,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_desensitization_rule',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1853,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_desensitization_rule_back_20211227',
    //     ifExists: 0,
    //     pid: 55,
    //     id: 2406,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_dynamic_page',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1854,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_dynamic_page_datasource',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1855,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_evaluation',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1856,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_evaluation_reply',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1857,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_flume_conf_to_topic',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1858,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_flume_host_to_conf',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1859,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_grafana_apikey',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1860,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_grafana_dashboard',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1861,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_graph_url_to_api',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1862,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_influx_list',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1863,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_influx_management',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1864,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1865,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_info_router',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1866,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_ip_whitelist',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1867,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_acl_apply_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1868,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_cluster',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1869,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_cluster_bak',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1870,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_cluster_copy1',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1871,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_cluster_machine',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1872,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_group_auth_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1873,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_group_auth_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1874,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_to_api',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1875,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_topic',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1876,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_topic_apply_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1877,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_topic_auth_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1878,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_topic_auth_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1879,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_topic_new_apply_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1880,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_user',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1881,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_kafka_user_copy1',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1882,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_app_node',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1883,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_instance_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1884,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_keyword_deploy_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1885,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_keyword_order',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1886,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_rule',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1887,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_keyword_alarm_system_info',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1888,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_log_manager_cluster',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1889,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_log_manager_system',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1890,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_log_manager_topic',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1891,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_log_manager_topic_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1892,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_login_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1893,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_message_template',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1894,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_project_feedback',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1895,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_request_limit',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1896,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_request_param',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1897,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_response_field',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1898,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sql_rule',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1899,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_alert_message',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1900,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_api_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1901,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_count_all_request_record',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1902,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_count_request_record',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1903,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_department',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1904,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_dict_item',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1905,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_dict_type',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1906,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_directory',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1907,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_permission',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1908,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_request_record',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1909,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_role',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1910,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_role_permission',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1911,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_user',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1912,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_sys_user_role',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1913,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_topic_to_api',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1914,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_version_update_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1915,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1916,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_edge',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1917,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_es_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1918,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_grafana_job',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1919,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_grafana_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1920,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_grafana_source_apply',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1921,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_influx_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1922,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_job',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1923,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_job_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1924,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_job_running_log',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1925,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_job_trigger',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1926,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_kafka_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1927,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_kill_job',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1928,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_node',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1929,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_node_bk20220112',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2931,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_queue_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1930,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_spark_streaming_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1931,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_storage_queue_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1932,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_api_workflow_storage_tsdb_model',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1933,
    //     status: 1,
    //   },
    //   {
    //     name: 'cmb_app_key_permission',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1934,
    //     status: 1,
    //   },
    //   {
    //     name: 'db_mysql_rule_test',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 3189,
    //     status: 1,
    //   },
    //   {
    //     name: 'db_mysql_test',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2924,
    //     status: 1,
    //   },
    //   {
    //     name: 'db_mysql_test2',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2925,
    //     status: 1,
    //   },
    //   {
    //     name: 'db_mysql_test3',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2932,
    //     status: 1,
    //   },
    //   {
    //     name: 'hdfsjsontomysql',
    //     ifExists: 0,
    //     pid: 55,
    //     id: 1945,
    //     status: 0,
    //   },
    //   {
    //     name: 'qrtz_blob_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1949,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_calendars',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1950,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_cron_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1951,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_fired_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1952,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_job_details',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1953,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_locks',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1954,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_paused_trigger_grps',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1955,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_scheduler_state',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1956,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_simple_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1957,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_simprop_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1958,
    //     status: 1,
    //   },
    //   {
    //     name: 'qrtz_triggers',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 1959,
    //     status: 1,
    //   },
    //   {
    //     name: 'zs_matter_info_test',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2926,
    //     status: 1,
    //   },
    //   {
    //     name: 'zs_matter_info_test2',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 2933,
    //     status: 1,
    //   },
    //   {
    //     name: 'zs_matter_info_test_rule',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 3190,
    //     status: 1,
    //   },
    //   {
    //     name: 'zs_rule_table_test',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 3191,
    //     status: 1,
    //   },
    //   {
    //     name: 'zs_rule_table_test2',
    //     ifExists: 1,
    //     pid: 55,
    //     id: 3192,
    //     status: 1,
    //   },
    // ],
    name: 'cmb-api',
    dbType: 'Mysql',
    pid: 0,
    id: 55,
  },
];
